apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
spec:
  ingress:
    enabled: true
    path: /
    hostname: app-monitor.local
  config:
    log:
      mode: console
      level: info
    auth:
      disable_login_form: false
      disable_signout_menu: false
    security:
      admin_user: admin
      admin_password: prom-operator
