apiVersion: integreatly.org/v1alpha1
kind: GrafanaDatasource
metadata:
  name: loki-datasource
  namespace: monitoring
spec:
  datasource:
    name: Loki
    type: loki
    access: proxy
    url: http://loki-gateway.monitoring.svc.cluster.local:80
    isDefault: true
