apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
patches:
  - target:
      kind: HelmRelease
      name: grafana
      namespace: monitoring
    patch: |
      $patch: delete
  - target:
      kind: Ingress
      name: grafana-ingress
      namespace: monitoring
    patch: |
      $patch: delete
