apiVersion: integreatly.org/v1alpha1
kind: GrafanaDatasource
metadata:
  name: loki-datasource
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  name: loki-datasource.yaml
  datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local:80
      isDefault: false
      editable: true
