apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 2.8.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    replicas: 1
    backend:
      replicas: 1
    read:
      replicas: 1
    write:
      replicas: 1
    persistence:
      enabled: true
      storageClassName: local-path
      size: 10Gi
