apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.59.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    adminPassword: admin123
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
      - host: app-monitor.local
        paths:
        - path: /
          pathType: Prefix
