apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.57.4 # adjust if you need another version
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    # Disable default ingress from chart
    ingress:
      enabled: false

    persistence:
      enabled: true
      size: 10Gi
      storageClassName: local-path

    adminUser: admin
    adminPassword: prom-operator

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://kube-prometheus-stack-prometheus.monitoring:9090
            access: proxy
            isDefault: true
