apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  releaseName: promtail
  chart:
    spec:
      chart: promtail
      version: 6.11.5
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1m
  values:
    config:
      lokiAddress: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
