apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: 6.59.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    adminPassword: admin123
    ingress:
      enabled: true
      hosts:
        - grafana.local   # fixed: only strings allowed
    persistence:
      enabled: false
