apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      # pick a chart version that exists in your grafana repo; adjust if necessary
      version: "5.8.3"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    # Run single-replica mode for single-node clusters
    replicaCount: 1
    persistence:
      enabled: true
      storageClassName: local-path
      size: 10Gi
    backend:
      replicas: 1
    read:
      replicas: 1
    write:
      replicas: 1
    # Use the gateway service name that chart creates for internal access (often loki-gateway)
    gateway:
      enabled: true
