apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.59.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    adminUser: admin
    adminPassword: admin123   # You can encrypt this later with SOPS if you want
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - name: grafana.local
          paths:
            - path: /
              pathType: ImplementationSpecific
