apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.57.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    persistence:
      enabled: true
      storageClassName: local-path
      size: 10Gi
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.monitoring.svc.cluster.local:80
