apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-instance.yaml
  - grafana-datasource.yaml
  - datasource-loki.yaml
  - dashboards/
annotations:
  kustomize.toolkit.fluxcd.io/depends-on: "operator"
