apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: default
spec:
  releaseName: mysql
  chart:
    spec:
      chart: mysql
      version: 9.10.8
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    auth:
      existingSecret: mysql-secret   # secret defined in secret-mysql.yaml
      database: wordpress
      username: wordpress
    primary:
      persistence:
        enabled: false   # disable persistence for simplicity (no storageClass issues)
