apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
  namespace: default
spec:
  releaseName: mysql
  interval: 1m
  chart:
    spec:
      chart: mysql
      version: 9.10.8
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: mysql-secret   # ✅ Use unified secret
      rootPassword: ""               # taken from mysql-secret
      username: wordpress            # app user
      password: ""                   # taken from mysql-secret
      database: wordpress            # db name
    primary:
      persistence:
        enabled: true
        size: 1Gi
