apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: default
spec:
  releaseName: mysql
  chart:
    spec:
      chart: mysql
      version: 9.10.8
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    auth:
      existingSecret: mysql-secret   # ✅ ensure MySQL uses your secret
      rootPassword: ""               # leave blank → comes from secret
      username: wordpress            # same as in mysql-secret
      password: ""                   # leave blank → comes from secret
      database: wordpress            # DB name
