apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: default
spec:
  releaseName: mysql
  chart:
    spec:
      chart: mysql
      version: 9.10.8
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    auth:
      existingSecret: mysql-secret    # ✅ use your secret
      rootPassword: ""                # leave blank → pulled from existingSecret
      username: wordpress             # DB user (must match secret)
      password: ""                    # leave blank → pulled from existingSecret
      database: wordpress             # DB name for WordPress
