apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: default
spec:
  chart:
    spec:
      chart: mysql
      version: 9.10.8
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    auth:
      existingSecret: mysql-secret   # ✅ ensure this points to your secret
      database: wordpress            # database name
