apiVersion: ENC[AES256_GCM,data:Z8A=,iv:MzN+wu5WEluzePNjHfN6fV8koTwLnfUvwEHkU0vo3R0=,tag:4iAlZOTxGdYS8fqv39eCSw==,type:str]
kind: ENC[AES256_GCM,data:RKN64Vn6,iv:iNphwxNyHPoDieVGiWMEZsX6cMOT1pqD10/4JbfgBEI=,tag:xAo3co5m7rElJcjGl6LueQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1UQE2yD41o+kdPfe,iv:1gSSwwQCnRd+177jGEKTpm/K4xD6wbSen/z0eKnHiVw=,tag:RIz5lELbgyZwxRsCd09xgg==,type:str]
    namespace: ENC[AES256_GCM,data:EURcP4tzjA==,iv:4nU2/lEbH9GufdOtnYtDmV3h1EzB1pCyzvWZye6QFxQ=,tag:pIxW7yZysADI0y2L67kfsA==,type:str]
type: ENC[AES256_GCM,data:IauM4LKx,iv:jXLBL5f6VFN8jNdNJuFY7pnm1fRUQsDi9z2a2ifY6z4=,tag:yiFQr05zO76LE4lrWIqKyQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:CnSE03GH4J/1SU1pT5TsBnRJRJI=,iv:ulokU7oiqlBd1D+IvGW5WO0YGF+nhv+iSGIboaf8K8w=,tag:M4YZMcc2NMgY5m9B/OUljg==,type:comment]
    mysql-root-password: ENC[AES256_GCM,data:FIofjotwAR6aDO4=,iv:zsB8PIDJUSHiy+yjYkvFoce1RJp49h9tsFDHEVXE10s=,tag:p+Bz4kj2lkj7uJXeGBxCpw==,type:str]
    #ENC[AES256_GCM,data:aElhgmsakypa5ZNPeHTy1i5UWR7M/c1bU/I=,iv:/HSbFFLsrjPRx18veXk2+H3kivj/IPge5dwXsf1whSE=,tag:i8H5eKQkBgKffHEtz0+gLw==,type:comment]
    mysql-username: ENC[AES256_GCM,data:6mJ0d/WmRNL5,iv:i6OV2pdmHEG//lC+yLVLxb+xEmNzgarLv2PO+Jaz4OQ=,tag:M8KddG0X/LmMl9O7U95WvA==,type:str]
    #ENC[AES256_GCM,data:M6L4vW4qSYe7VBgvE/6W4Ko=,iv:9+CNbUKlt3n4EnCCBwjRpx/aKOAFwGS/A77f2IfCSSk=,tag:QiLNvXS22VFCUHDhLlMoiQ==,type:comment]
    mysql-password: ENC[AES256_GCM,data:MM5QopqiRGAgazw=,iv:r69nDEElVI+pRc16Vys3j1TvcdcODZScLLwnW7Tuwzw=,tag:0ZAsAyz/zoGKez0uDn3G/Q==,type:str]
    #ENC[AES256_GCM,data:AD8yd/71eEVh5v4fHkDW0rXv/Zo+XA1vKMnaR4N9hSiHjgJuaw==,iv:yazFAmzblVAOKbzuUGdCr1dlvTq+POipUOIM/KqcEOM=,tag:5oLnExkTUH+yoERO1Dfg3Q==,type:comment]
    wordpress-password: ENC[AES256_GCM,data:OdFDunI5x9S3Rzk=,iv:izJXM/DCwx5oC/BTc2h4GUsyIOMtpHOgKaVYZo2gotg=,tag:N//ss1UrWdg4JnbPYLaMRg==,type:str]
sops:
    age:
        - recipient: age1ae36uc76hcjlldeq6ch7pa6s5xz0zdssmp9hjy37eyt8vqugaepqsc2j8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZFJCTndsZGYvOWl2MzJa
            V0ZoSlFRMkRKTFU4OVg1OUVlR0o3dHR4d2hzClVHQUswRHp2S0U2dUtTVVdaREE2
            b0FuSVJIczJSb1p2VXc5V3o0WllSTUUKLS0tIDcyZUZJVjBXdEw2cmZtM2FQdUo1
            TEJHQVhJTXhsQWdrOVRsSVlQUHRmN3cK7eT9E0HICdDSq450cuNddJq+Rjly/uxN
            L8WeH4W9qJjc05N7+7xBmSqA/lcyu2MvHVt7DURgIKqP+mqCXGtTzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-13T16:45:02Z"
    mac: ENC[AES256_GCM,data:Wl3cLeVRzBFWEfI4aqK5VkMDWsrBSQmnDkT5Ab+8P4OusKK+0trdehOp+AcLR3WsIHWq4KIo5yjAy8QnCJ3FtQbYjW1DaJnPsT4ae8HIzXA+pknKjmFKi4wAzSO/n1ZQuB2uc9E+bh7g4VeKgqGSU1vyE4t7vVBTyJeixSruMw8=,iv:dr2clpZlM5jyNySzBklv+n3v5+IZHxMYiHXr5RPxM3o=,tag:d/UFxedAs2Ff5FyGdJgomw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
