apiVersion: ENC[AES256_GCM,data:lP0=,iv:D7vsCWSUpzhCEb0+X7ECEa0tlRGX0TbVwbxO53zfe5M=,tag:GDJdrbFLkvmAb6m7yvwBIQ==,type:str]
kind: ENC[AES256_GCM,data:Pp4MJBvB,iv:rSKCWUrpTnElApGWz8TtaBF9s+ds7/acjE7gzJeAn5s=,tag:rCz3tgE6l0+vhwVaqCUvmw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:u+yxXuPwXl3bL2G0eQ==,iv:ZNDcc7yMMtylyOgTZg6UQHRNKfjWUAmvvFEUgY/+wMw=,tag:FmLd1qmHcOlSOCq+x5bwWg==,type:str]
    namespace: ENC[AES256_GCM,data:G573SHJvPg==,iv:kgSBsgY6q3haZI3nhPbgyHDIu3wknKFDjGoktcJiHCU=,tag:1ZieCIk24nirSRo7s7jNEw==,type:str]
type: ENC[AES256_GCM,data:i5r6sQ5c,iv:rdoR2B5HjEbyrs2ZxoHvXK5QsWDHuyCZWiHsmcuVdQs=,tag:bGgo79PKlvZGZqlRVaa5AA==,type:str]
stringData:
    mysql-root-password: ENC[AES256_GCM,data:dpEK06UyLTt8vQ==,iv:4L6dW8irYKRg/Ow6QfCCbpTgyPIVeNgB3RM2NEM8H8s=,tag:ljq4JK+OMHwmecMwzTo87w==,type:str]
    mysql-password: ENC[AES256_GCM,data:vhKpARmaxImn86B8EfK3,iv:QuVZtfzimLvBYaCDTIlgwNlR7lLNTwo1Awr2Vb90Ek8=,tag:0NCn32mUftG16X3JJ9zgRw==,type:str]
    mysql-user: ENC[AES256_GCM,data:XsYYmzM7aIAo,iv:kdp0GtyLEmOFHEa4luCTH71+Y5mqcobufMpYsxf3md0=,tag:n377kN7VHiINDPo7sEQDdg==,type:str]
    mysql-database: ENC[AES256_GCM,data:yiUNvj6RikfY,iv:bDEvXU3txF+bB0oCg6eiFsn++4nnpUfMmzFfjeNtqvw=,tag:ecfdy0pOUxTNuaCwrDQYyQ==,type:str]
sops:
    age:
        - recipient: age1ae36uc76hcjlldeq6ch7pa6s5xz0zdssmp9hjy37eyt8vqugaepqsc2j8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdUowUHE4MDVIUnNrY2U4
            NlNnTlgycXY3aEZJRkFIU3duVzJOamtIMWdjCjFZenZiNFN1Slp2cnVBMWMzTmhZ
            aVJwSFRwS0gvbzY3SEdXZ0c0SVE1UnMKLS0tIFh3bWJZdXc1SVdndjRKUjJuYUpB
            S3JEWEVWcnV2SlE5b0NVaWR6TG10clUKpsWIxHJR0LHI4nIpbR5yC0DzGM4Y8G4o
            Ql+xaZVnnytYem3wd9kB45aQl6GCPF3CqYpszrkZ3aIIGB4+YkoFdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-13T09:51:32Z"
    mac: ENC[AES256_GCM,data:B2EVhCdLQ3f951HWy4e5ymETOASe2QU34hs2E4IZLSrfgfIkrv1QPQsvANfJuiZ7yAO2UILYs24ZdkJskwQajEthgD71WGtC+2LVWDHVvKt+r7zjV4GwtzYrXbQSnb5HkbSAMkcgOi0cR4BYy8mfYqmpFfpbmOI8cVzuvhSsRIU=,iv:ixdz+0EgNaFBFsiulLzVex0pMtMHdWxrPAxOmgC1NNA=,tag:tl14KDqMlH3IOyAeBA9PXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
