apiVersion: ENC[AES256_GCM,data:n8M=,iv:tEjLEvAqm90U5SkoXj1StowTckS8Gg/VY+5UmxTGbYE=,tag:9lW3ppdk5BO1+0i0VZuRAw==,type:str]
kind: ENC[AES256_GCM,data:WN0Knn79,iv:N0He/M+KdszjSe3HKyLs6hJcB5lxarLZ3hWQN6OJ6Ks=,tag:oROAq4yw9SAyZANb6lZ7ng==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fWc60nMfHi4E0YEy,iv:2TxWGOTzwBsHUzB2dwNhiWb+Da5JRanMYcBbYYPoVWM=,tag:Iw1qJymNG1ENp3WWZKl6ew==,type:str]
    namespace: ENC[AES256_GCM,data:CTxo7Km0yA==,iv:pzGcYx3VVU5xm+9cxQDjHR3MkNj6LKUsiFkjbt7/8M0=,tag:kA6RsY5OS3Y6idPg7hEztQ==,type:str]
type: ENC[AES256_GCM,data:myuo4mnJ,iv:LFLjJqbw12oyFNXvbseDm5t20ONDdKH9JQT6fV/0JeQ=,tag:td6UKcYgIzBrOM0Jnji//g==,type:str]
stringData:
    #ENC[AES256_GCM,data:jpEXDWmN5+KTyBzad7iBodHFrhJJt/c4VoI8polZ,iv:HaCSQAHR6PnOeZYEZA/GH7vJOutY007jKspvs0G1oGA=,tag:QZc3lCCRW9Frgq17ZRFWEg==,type:comment]
    mysql-root-password: ENC[AES256_GCM,data:RywaioaZglVD5iA=,iv:/Xc6KhnjWMPPgNgwPZ+rHC+DGfRI+01xewRTrtXnC98=,tag:Pie6RV+j1WQnDGfjMog/hg==,type:str]
    #ENC[AES256_GCM,data:SLJX5LBnQp3kC2JSCl8Fd5Qgl1QJmHlWM6HVGNc1x6vIZPOXFmQD,iv:Y2NZ/1LSUljFJqxpUrRnV5UixPBU85Yk4aYOfkoTUp4=,tag:shpLzYBh8V1HdvBLyUXgKQ==,type:comment]
    mysql-username: ENC[AES256_GCM,data:RBXUQNdCN0rK,iv:eEFhBcnzo0EONrCCSaf7BllTGzmiCL4sZnyEdn+dU0Y=,tag:q4XPqN/TSt+Q99uCY7uQMg==,type:str]
    mysql-password: ENC[AES256_GCM,data:3AznaiFNLsPTIPs=,iv:mnS635fac1udFyyE/hZM1Dl4UfAApvkSve0f5ircHE0=,tag:x8Hd0ZD2NRSJz80AthesZw==,type:str]
    mysql-database: ENC[AES256_GCM,data:Wr83KesgLkDj,iv:PrVKNZhhFxxQGL560fGUGo24Zs8KVyCKyycI64pRuVk=,tag:srYdbYoVy9S79baWCkSAJQ==,type:str]
    #ENC[AES256_GCM,data:JfQI177GuNStkWlpfApwAgicbILF2IA3kuh6BjSK,iv:YVo6lXVYP+3sPBkMbLAxN/Ye8WFQP3YbgPjoVNqRhc8=,tag:MjJGm04w52/jdepRSlRK/w==,type:comment]
    wordpress-username: ENC[AES256_GCM,data:ASoccfY=,iv:VNeguSaTOAzxHURGCxZllBMd1lAqRS2g7eYmG6sBDb8=,tag:HyEREhxbORQXSDn1C37Cdg==,type:str]
    wordpress-password: ENC[AES256_GCM,data:ES7eWbYDUxZVJlY=,iv:F62uom9ma+weUMcqa7dUOojv3/cy7BI5VArzdyE0I2M=,tag:n8ATup1ZJuDr4UQmZSCo9A==,type:str]
sops:
    age:
        - recipient: age1ae36uc76hcjlldeq6ch7pa6s5xz0zdssmp9hjy37eyt8vqugaepqsc2j8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncy9mMmxacVNIY2tIU2Vj
            WmxwSkt3amdDejZHQ0ZPSUxSd0twMWdWc1ZzClBkYUlMODBrTmhIbngxc095ejF0
            MzhZWmdxdlBSOGs5Q0xTWWU2ajNVYzAKLS0tIERESVhPczdzNGFhNHlEbHMvV2ow
            eDQrRkV2K3RpTnVwOUpVNXdCQ3Fma0EKLo8YG9HpmVv1H/CPfJ6ToBvk+z2MBlh5
            9EqvEOkYUpAR7WAn/r2Daeqd+cjDRfrvtz4N3bM+xItEmcT/9GVIBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-13T16:59:34Z"
    mac: ENC[AES256_GCM,data:j2Lb8EHo8N8UEbfzZuKWSECqz4BPc5bM3dXq1gW3ykTWwI++JpHhMHwhWY9z2gsdV98IZUF/0PpmDGujze4W3NEOCCE7pmYtJ8hIzjhgOD9Y64lyFZPflfycuZicHJWA7Mw7b/CByvFdt5DSkDA771ixr0ZCmfpTdrLNLfhZShs=,iv:C7g9R1Pj/j1aTcHcTTr4kgc8Wl7sEFVAWbeQZmg66uQ=,tag:z8z6BIj+3YrcswI2yayi0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
