apiVersion: ENC[AES256_GCM,data:/zw=,iv:AcbSO0YUGsGYaX4gThHroR0HaWaaV9T5VS4EqIEK7hQ=,tag:ARAyyQNASmAm3nNxBcBJUw==,type:str]
kind: ENC[AES256_GCM,data:zD1e9j0S,iv:lmAPP0H+YoUmJ2VpXzDoKX44B5mcJsW3LmK1wyttbNk=,tag:1a4nFou+7xkFgoib4wDT6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:brMSWihMr+tMoRMo,iv:tqCIlnZC/0J7P7pEBnfz3baUYhntpXeo1AVLeBj8rgs=,tag:VKMu2y+9A90OLoClTS/HDg==,type:str]
    namespace: ENC[AES256_GCM,data:LzXLdTsoaw==,iv:7WoCtX0F+v2GihCrdtG6J9OaXqJUt/zibTXg6kCA7QU=,tag:j4p0KGDPOlGxemfxKiAKyw==,type:str]
type: ENC[AES256_GCM,data:B84e7BLh,iv:ieACfoytM8ItLzcMzJLPJp2B3doDogCnFH9XLkeJ4Hw=,tag:UyVDsrlibW0vbQSATUhA+w==,type:str]
stringData:
    #ENC[AES256_GCM,data:iUtehw8V4X5RPvEuPVjGgwSkTw+tHc6Qhopi+72B,iv:vHmhxR4Wq7gRhRfHhC9TwTEuA6wNqYgQm81vgTeRbMA=,tag:uVirMW52Ej4H5SKgKo6inA==,type:comment]
    mysql-root-password: ENC[AES256_GCM,data:SqQEGK+UikoF2RM=,iv:9sW+EjSfaNs3m6pLpK4aIvOEBFF2Deela5O3ceOaF7Y=,tag:IH+9PtmLMStGTSJ11HYk3Q==,type:str]
    mysql-username: ENC[AES256_GCM,data:GUryK19Qx3PZ,iv:eYl2U6J5i/v1UBEnATxcFJCsv+ybPxj1NCXu4IkWw1o=,tag:HribkCFtQjoOSaZ1tmNSjw==,type:str]
    #ENC[AES256_GCM,data:u8fAy2JM4K46a1QCusisT5YVvbba0ITVTiziIg==,iv:yr+H9pNJ/Xqle77HWrUxeQ6eIerVHicFXbM9UEeZlek=,tag:gSr0HWqhY0OnovSRXsBFFA==,type:comment]
    mysql-password: ENC[AES256_GCM,data:esw0Ul8Vsngzz+A=,iv:tnAnZnNckVjnn4IomJ7zBDBIUAWTDEjE6OMzK6NIpRE=,tag:DvUVAHGoxxxIGFaeLuCKiA==,type:str]
sops:
    age:
        - recipient: age1ae36uc76hcjlldeq6ch7pa6s5xz0zdssmp9hjy37eyt8vqugaepqsc2j8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNm55ang0NVcwRys2dzNL
            aXYwWHRhNDdVMEZCRmRWOW50QVB3QzNtN2dvCkZZMURvMWtIeFowYkYyenJleGM1
            VER2VkZZY1gyTml3UVZhMlo3ZWxUTEEKLS0tICtjeTM5ZG4rb1NIRSszYWZSVHFB
            QnZlYmNMRUNRTnZJYUVoeUpXZFhEL0UKelxQOz11tbKfjNlZfXkmN7paqpqn73n5
            YyoXL+VoUxMYL+3GC7pQU3In9M8lPCW5wVyGdOfwXIB2xtH/1QUhqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-13T16:02:13Z"
    mac: ENC[AES256_GCM,data:HF5XYFAzb2OrEXK5TvE6v6vQ5atqUWcCl5X+gdhuS2TxCHnTIoHNdpuydOUPXluc5GqEM4CozdrXkTRBKXMIQzEJMNLqSDTfozr0zHPECXTXlfGmBsFekMF6HIXP+Q7dw5rGVbieUoQMzTwsceWe2QT5AHxmSa1PovcxR+vlt44=,iv:iLqM5UnM8CsLc4uII1cMXMDEO8547r1AA+IlJNDoPXs=,tag:Q3FQ6mBFVJo4Fx86MfDT6Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
