apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system   # ✅ must be flux-system
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
