apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system        # Flux must watch this namespace
spec:
  interval: 5m
  targetNamespace: metallb-system   # MetalLB will actually be installed here
  install:
    createNamespace: true
  chart:
    spec:
      chart: metallb
      version: "0.13.12"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
