apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system     # must be flux-system
spec:
  interval: 5m
  targetNamespace: metallb-system   # where MetalLB will be installed
  install:
    createNamespace: true
  chart:
    spec:
      chart: metallb
      version: "0.13.12"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
