apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.0                # ✅ adjust if you need another version
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 5m
  values:
    controller:
      replicaCount: 1
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
      ingressClassByName: true

      # ✅ Lua plugin integration
      extraVolumes:
        - name: lua-plugins
          configMap:
            name: ingress-nginx-lua-configmap
      extraVolumeMounts:
        - name: lua-plugins
          mountPath: /etc/nginx/lua/plugins
          readOnly: true

      # optional metrics
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
