apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.10.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      replicaCount: 1
      service:
        type: LoadBalancer
      extraVolumes:
        - name: redirect-404-plugin
          configMap:
            name: ingress-nginx-lua-configmap
      extraVolumeMounts:
        - name: redirect-404-plugin
          mountPath: /etc/nginx/lua/plugins/redirect-404-plugin/handler.lua
          subPath: handler.lua
          readOnly: true
