apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.1 # use the version you want
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      replicaCount: 1
      service:
        type: LoadBalancer
      config:
        plugins: "redirect-404-plugin" # enable our Lua plugin
      extraVolumes:
        - name: custom-lua-plugins
          configMap:
            name: ingress-nginx-lua-configmap
      extraVolumeMounts:
        - name: custom-lua-plugins
          mountPath: /etc/nginx/lua/plugins/redirect-404-plugin.lua
          subPath: redirect-404-plugin.lua
          readOnly: true
