apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.10.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      config:
        plugins: "redirect-404"   # ✅ register plugin
      extraVolumes:               # ✅ mount configmap with Lua script
        - name: lua-plugins
          configMap:
            name: ingress-nginx-lua-configmap
      extraVolumeMounts:
        - name: lua-plugins
          mountPath: /etc/nginx/lua
          readOnly: true
