apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 5m
  values:
    controller:
      replicaCount: 1
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
      ingressClassByName: true

      # ✅ Mount our Lua plugin ConfigMap into NGINX plugins dir
      extraVolumes:
        - name: custom-lua-plugins
          configMap:
            name: ingress-nginx-lua-configmap
      extraVolumeMounts:
        - name: custom-lua-plugins
          mountPath: /etc/nginx/lua/plugins/redirect-404-plugin.lua
          subPath: redirect-404-plugin.lua
          readOnly: true
