apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      replicaCount: 2
      ingressClassResource:
        name: nginx
        enabled: true
        default: true

      # ✅ Extra Lua plugin volume & mount
      extraVolumes:
        - name: redirect-404-plugin
          configMap:
            name: ingress-nginx-lua-configmap
      extraVolumeMounts:
        - name: redirect-404-plugin
          mountPath: /etc/nginx/lua/plugins/redirect-404-plugin/main.lua
          subPath: main.lua
          readOnly: true

      service:
        type: LoadBalancer
