apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.7
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        type: LoadBalancer
      # lua plugin configuration
      config:
        lua-shared-dicts: "plugins:10m"
        # register the plugin name (must match the configmap key filename without .lua)
        plugins: "redirect_404"
      # mount the configmap into the controller pod
      extraVolumes:
        - name: lua-plugins
          configMap:
            name: ingress-nginx-lua-plugins
      extraVolumeMounts:
        - name: lua-plugins
          mountPath: /etc/nginx/lua/plugins
          readOnly: true
