apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.1   # adjust to the version you are using
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 1m
  values:
    controller:
      extraVolumes:
        - name: custom-lua-plugins
          configMap:
            name: ingress-nginx-lua-configmap
      extraVolumeMounts:
        - name: custom-lua-plugins
          mountPath: /etc/nginx/lua/plugins/redirect-404-plugin.lua
          subPath: redirect-404-plugin.lua
          readOnly: true
