apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-lua-plugins
  namespace: ingress-nginx
data:
  redirect-404-plugin.lua: |
    local _M = {}

    function _M.header_filter()
      if ngx.status == ngx.HTTP_NOT_FOUND then
        return ngx.redirect("https://www.google.com", ngx.HTTP_MOVED_TEMPORARILY)
      end
    end

    return _M
