apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-lua-plugins
  namespace: ingress-nginx
data:
  redirect_404/main.lua: |
    -- Custom plugin to redirect all 404 responses to Google
    local _M = {}

    function _M.header_filter()
      if ngx.status == 404 then
        ngx.header["Location"] = "https://www.google.com"
        ngx.status = 302
        return ngx.exit(302)
      end
    end

    return _M
