apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-lua-configmap
  namespace: ingress-nginx
data:
  main.lua: |
    local _M = {}

    function _M.header_filter()
      if ngx.status == ngx.HTTP_NOT_FOUND then
        ngx.log(ngx.ERR, "[redirect-404-plugin] Intercepted 404, redirecting...")
        return ngx.redirect("https://www.google.com", ngx.HTTP_MOVED_TEMPORARILY)
      end
    end

    return _M
