apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repositories-kustomization.yaml
  - monitoring-operator-kustomization.yaml
  - monitoring-resources-kustomization.yaml
  - apps-kustomization.yaml
  - metallb-kustomizations.yaml

