apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps-disabled/monitoring/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
