apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wordpress
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/wordpress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: mysql
    - name: ingress-nginx
