apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 5.8.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: local-path

    # Force local filesystem instead of S3/GCS
    loki:
      commonConfig:
        path_prefix: /var/loki
        replication_factor: 1
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
