apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-release
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/infra/metallb/release
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: metallb-release
  path: ./apps/infra/metallb/config
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
