apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      version: 15.2.21
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    mariadb:
      enabled: false   # ✅ disable bundled MariaDB
    externalDatabase:
      host: mysql.default.svc.cluster.local
      user: wordpress
      database: wordpress
      existingSecret: mysql-secret   # ✅ use your secret
      password: ""                   # ✅ pulls from secret
