apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      version: 15.2.21
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    wordpressUsername: admin
    wordpressPassword: ""                # leave blank → comes from secret
    existingSecret: mysql-secret         # ✅ tell WordPress to use mysql-secret
    mariadb:
      enabled: false                     # ✅ we already run MySQL separately
    externalDatabase:
      host: mysql.default.svc.cluster.local
      user: wordpress
      password: ""                       # leave blank → comes from secret
      database: wordpress
      existingSecret: mysql-secret       # ✅ reuse same secret
