apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  releaseName: wordpress
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: 15.2.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    wordpressUsername: admin
    wordpressPassword: changeme
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql
      user: wordpress
      password: changeme
      database: wordpress
