apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: 15.2.33
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    wordpressUsername: admin
    existingSecret: wp-mysql-auth
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql.default.svc.cluster.local
      user: wordpress
      password: mywordpresspass
      database: wordpress
