apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      version: 15.2.33
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    wordpressUsername: admin
    wordpressPassword: ""                   # from Secret
    existingSecret: mysql-secret            # 👈 use our custom secret
    mariadb:
      enabled: false                        # 👈 disable bundled MariaDB
    externalDatabase:
      host: mysql.default.svc.cluster.local # 👈 MySQL service
      user: wordpress                       # from Secret
      password: ""                          # from Secret (mariadb-password)
      database: wordpress                   # DB name
