apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  chart:
    spec:
      chart: wordpress
      version: 15.2.33
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    wordpressUsername: admin
    wordpressPassword: wp-pass-123
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql.default.svc.cluster.local
      user: wordpress
      password: wp-pass-123
      database: wordpress
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: wordpress.local
      annotations:
        kubernetes.io/ingress.class: nginx
      tls: false
